### ISSUE TITLE
clang-tidy: macro replacement list should be enclosed in parentheses

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#1420]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): `main`
- Which version (or `HEAD` for the most recent on git): `HEAD`
- Any specific OS or system where the issue occurs? CI
- Any special versions of ROOT or Geant4? n/a

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. https://github.com/eic/EICrecon/actions/runs/8974103877/job/24645948859 for workflow
2. https://github.com/eic/EICrecon/actions/runs/8974103877/artifacts/1477589010 for artifact `clang_tidy_fixes.yml.zip` (400 B)

### Expected Result: (what do you expect when you execute the steps above)
No issues flagged; no failure to report issues if there are issues flagged.

### Actual Result: (what do you get when you execute the steps above)
`clang_tidy_fixes.yml` with:
```
Diagnostics:
- BuildDirectory: /home/runner/work/EICrecon/EICrecon/build/src/utilities/eicrecon
  DiagnosticMessage:
    FileOffset: 0
    FilePath: ''
    Message: macro replacement list should be enclosed in parentheses
    Replacements:
    - FilePath: ''
      Length: 0
      Offset: 15074
      ReplacementText: (
    - FilePath: ''
      Length: 0
      Offset: 15088
      ReplacementText: )
  DiagnosticName: bugprone-macro-parentheses
  Level: Warning
MainSourceFile: ''
```
Because offset is byte-wise, it's hard to figure out where exatly clang-tidy wants the parentheses to go...
